# Generated by Django 3.2.10 on 2024-01-08 16:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EmployeeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_type', models.CharField(blank=True, choices=[('RESIGNATION', 'Resignation'), ('TERMINATION', 'Termination'), ('REJOINING', 'Rejoining'), ('OTHER', 'Other')], max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('last_working_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.userprofile')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
