# Generated by Django 3.2.10 on 2024-01-08 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='company',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='company',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='company',
            name='start_year',
        ),
        migrations.RemoveField(
            model_name='company',
            name='timezone',
        ),
    ]
